@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.wind;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;