@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.dialog.script;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;