@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.datagen.builder;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;