@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.utils;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;