@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.event;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;