license="${mod_license}"
issueTrackerURL="https://github.com/Tictim/Paraglider/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://www.curseforge.com/minecraft/mc-mods/paragliders"
logoFile="icon.png"
authors="${mod_authors}"
description='''${mod_description}'''
enumExtensions="META-INF/enumextensions.json"

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
