@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.client.dialog;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;