@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.loot;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;