@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.capabilities;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;