@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.capabilities;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;