@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.contents.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;