@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.mixin;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;