@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.network;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;