@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.datagen;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;