@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.contents;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;