@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package tictim.paraglider.capabilities.wind;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;